version: '3'

services:
  base-api:
    extends:
      file: docker-compose.app.yml
      service: base-api
    depends_on:
      - qdrant
      - pgdb
      - redis
      - minio

  qdrant:
    image: qdrant/qdrant:latest
    mem_limit: 450m
    ports:
      - '127.0.0.1:${QDRANT_PORT}:6333'
    volumes:
      - ./data/qdrant_storage:/qdrant/storage

  pgdb:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - type: volume
        source: pgdb-data
        target: '/var/lib/postgresql/data'
    ports:
      - '127.0.0.1:${DBPORT}:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}

  redis:
    image: redis:latest
    user: '999:999'
    # command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '127.0.0.1:${REDIS_PORT}:6379'
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

  redis-ui:
    image: patrikx3/p3x-redis-ui:latest
    depends_on:
      - redis
    ports:
      - 127.0.0.1:${REDIS_UI_PORT}:7843
    volumes:
      - p3x-redis-ui-settings:/settings

  # Use minio to mock s3
  minio:
    image: 'minio/minio:latest'
    ports:
      - '9000:9000'
      - '9090:9090'
    environment:
      MINIO_ROOT_USER: 'root'
      MINIO_ROOT_PASSWORD: 'password'
    volumes:
      - 'minio:/data/minio'
    command: minio server /data/minio --console-address ":9090"

  marker:
    image: marker-app:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      - ./data/marker/datalab:/root/.cache/datalab
      - ./data/marker/uploads:/app/uploads

volumes:
  pgdb-data:
  pgadmin-data:
  redis-data:
  redis-conf:
  p3x-redis-ui-settings:
  minio:
  node_modules:
